version: "3"
services:
  app:
    image: is332-app:latest
    container_name: react-app
    restart: always
    build:
      context: .
    volumes:
      - ./:/app/src
    ports:
      - "3000:3000"
